### ISSUE TITLE
Horizontal scroll bar appears when switching animations on the demo page

### ISSUE THREAD

**Issue by PhenixR** [cyan33/react-animation#5]
When the effect is switched, the bottom scroll bar appears suddenly

**Comment by cyan33** [comment]
Can you provide some screenshots?

**Comment by PhenixR** [comment]
This is the bottom scroll bar
![scrollbar](https://user-images.githubusercontent.com/30428176/34674691-d6dbcc68-f4c1-11e7-920c-da768b29c00b.jpg)

**Comment by cyan33** [comment]
Sorry, I cannot identify the problem based on your description. I think it could be better if you provide more details, or you could fix it yourself and submit a PR. I appreciate that very much! 😄 
  
To run the dev mode, fork the repo first and run:

```sh
npm install
npm start
```

**Comment by PhenixR** [comment]
秀

**Comment by cyan33** [comment]
Fixed by @PhenixR via https://github.com/cyan33/react-animation-wrapper/pull/9
